$env.config.show_banner = false
$env.config.edit_mode = "vi"
$env.config.buffer_editor = "nvim"
$env.EDITOR = "nvim"
$env.VISUAL = "nvim"
$env.TERMINAL = "ghostty"
$env.BROWSER = "cha"

source commands.nu
source prompt.nu

# Generated by env.nu from the installed tools, never checked into dotfiles.
source ($nu.cache-dir | path join $"init-($nu.pid)" "atuin.nu")
use ($nu.cache-dir | path join $"init-($nu.pid)" "mise.nu")
rm --recursive ($nu.cache-dir | path join $"init-($nu.pid)")
# mise's initial activation emits PATH as a string; its later hooks use lists.
$env.PATH = (if ($env.PATH | describe) == "string" {
    $env.PATH | split row (char esep)
} else { $env.PATH }) | uniq

# The helper returns only agent environment values. flock serializes startup;
# --close prevents a daemonized ssh-agent from inheriting the lock descriptor.
const agent_helper = path self ssh-agent.nu
let agent_dir = $env.XDG_RUNTIME_DIR? | default ($nu.cache-dir | path join "ssh")
mkdir $agent_dir
if ($env.XDG_RUNTIME_DIR? | is-empty) { ^chmod 700 $agent_dir }
let agent = do {
    ^flock --close ($agent_dir | path join "dotfiles-ssh-agent.lock") $nu.current-exe --no-config-file $agent_helper $agent_dir
} | complete
if $agent.exit_code == 0 {
    hide-env --ignore-errors SSH_AGENT_PID
    $agent.stdout | from json | load-env
} else {
    print --stderr $"Nu: SSH agent setup failed: ($agent.stderr | str trim)"
}
